apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: dummysites.stable.dwk
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: stable.dwk
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    kind: DummySite
    plural: dummysites
    singular: dummysite
    shortNames:
    - ds
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                website_url:
                  type: string
                image:
                  type: string
      additionalPrinterColumns:
        - name: URL
          type: string
          description: URL to the site where its HTML will be collected
          jsonPath: .spec.website_url