apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      # volumes: # Define volume
      #   - name: shared-pingpongcount
      #     persistentVolumeClaim:
      #       claimName: pingpong-claim
      containers:
        - name: pingpong
          image: PINGPONG_IMAGE
          envFrom:
          - secretRef:
              name: postgres-dbpassword
          resources:
            limits:
              cpu: "100m"
              memory: "100Mi"
          readinessProbe:
            initialDelaySeconds: 10 # Initial delay until the readiness is tested
            periodSeconds: 5 # How often to test
            httpGet:
              path: /healthz
              port: 7000
          # volumeMounts: 
          # - name: shared-pingpongcount
          #   mountPath: /usr/src/app/files