apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-dbpassword
  namespace: applications
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAK7suq3IpXoyc8LprNMYcIhGiwabI/999+C5sJW9QqVGqRcyC895UVRjh7E4fY6s2/lxQCrl9CLPNEYcXv38oK08iYKP4dzodoOPJmSVtc6LL6yflBZTDmjmzfUTpVjA9Y4tHbFdokTNpQWD6g1Ls9By43o3OyeGboWhbdTKuW9JhNUMzpXwLvj8zzyeFyH4CUsUkSze72lrEP3CXGhguP0uqLYavNdmv5XPlbtPkXYEmf4bq3sjZ5E8obVqlD5E8E5QpuPv2ZVmCFqQYlBp4tbR9ZHkRmJq6Pdsvw0b+TFInhV9u+tCxZc52Y9jMkeoho8JRx955Lo2WwZORAb0TFl+c0cKtTaFUyiNxfyKAFxLKQsL94pG+aAzs8s/HbmzAGhiFyTC/PQYPdrTarix+cfLRtREKp1/4GaXbVHXFFsLLPs6PmN8xMXpfR0sVb3tzA9Nx1l9YYLqKNjpmA6PzW9+I5zNlEfDhpDyzM2JUAtJO1Gqb0Dg6vMupWQeSeA5QgqrZp4Zu0FD+bgxP/CYJXyAbyaUIiY+qhc7+HFvcsHhKggKRB15kbv3gyg6JIERmOWSpoP8HY0SRZDQhg/rrx7MKw+jhPeLVdbgaXNT7CDNNMOO2tKYCvq0MWOx8ufkWPtb6sxPhojUqX9SRjOjPFyX4D1M1nq5ORg7htkCLRFVJqQ4GlsI5UadjH7WtY6E2gzwbPrE92F4QbYA==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-dbpassword
      namespace: applications

