apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-dbpassword
  namespace: default
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBOwCUCOjU71c5EqiuoihBAk8BYHKDgl44QQVMPxl5J04wOGEmWJpVE9RTWp6g8Z74ALkHLZqQbq1DqzWpKGmm5N3I0ic7S8zr2AUNjOmjpCKuy7XCnqEw+ah6Y7jD5DuPy+Ebaomt9EGFmsntR5xOWT5fyuwmzataNAD3hNjWzHI0N4u4XTOTtddrAJiVfs0vkBg/bKhWZbbbJ05jXkzP58V49aqsUvU9X6zfKYrzPP8XwMlsJR06JPw6IJf4OhmTlifzBreg0gE+9oCYo/05UKHe7tdsDtR6Rdj8qu7WtjuqWiK0mjGEa/0iz8Hpsq1XY3TS0Ay3M5tGXRn6yh6+SkKacX6e3Bqg3Or1/0Q+hH+axm4NIx60mP+frG39jjaC9C/axbQwlf/AA7QaBRBW6TK7PNC8wn5iwgReYMV/7/nuyg6gjx9Bxtgf523b8whLXGYepGpJLO3zjpBNdLqHD99SuTBk7p0D3eRZBKFviRZ3kPj//EZHiIc/WAf6KkrJK4j1+FUf9CpnZwx3/m+cOgsd2u94qzpi4GarNMr/3oAg4hLVRmCpUpypwWQ17EURFXJM9bO8uRBH0AufhXzN041mGKi0Xy2bv83vOzAxo6CEIecluBbvbZqIUBDwbksrRLNtrUwJn5xJbwYUrn6RowVQiyyPBw+3bKdWV21UhvWLoTyxhWlnmqytFYilZWVgfeMZfKNP+3IUAew==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-dbpassword
      namespace: default

