apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-dbpassword
  namespace: applications
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCjjxl/NHFZVxaLXK8tuA7izTlomP4YeqoIXhXuLsKF8yt6mooYOddw646lWia6qktqaof3lotUceFBEUU17c5c/Q05H9uz800YdUPb5egsNV7H0LVC6TPgPr7AGPrQziG8g/aAJCdKlyB5yUH9gjLxa1kJpQVWj9cN52QZpQ9kZLbVR1+FLyf1T34LSQAFf7q1ujIVJZPMNOoj0UgIMIGOst+fFvjvwMfcaHuosoB4W8KHmnCGS/Z7LZTVkoHSsbwzfkA8lgEAsrzGRtMyTB1phg2wEJjvntz7hoCSogCCUUPyUWp1xllFQJuQMWLKrdv9LwdgCUjFUTXlkuF15QEvPjsSdRropHRrPfeN3EVYC2BjGBNR+DVCKhNuiTuxuR+tMc9jdFt+9xd+Z7A66l4MPk9fXio8DnrFSbdqi8RkYx2EYJG1UxJ8rW3ot0nc/OXK0MQUckT2whaQ1vaxX6JocfSVzi55H1D6gEWk/61s1AOwSwuw7IQ+6Sj4ysDUiDUERmNGY0ST98rF1k1iJNunBExDbN8kUYUzmH1GSyWg9DGqlaRvx/W+CblOIeMMc734K/tjxWKJSLvUoWDRuRlUsnlnkr8BNuTpuwl2BxN8y0gfP6dTmuRtKoQL1scaroxZ3r4RqYYmamWWCoKFXQ/5j5cldsfaT2ewVyXgyFODy9RHYORd/oakj48R4cDM+S60Z3VtpTQiTa4bxA==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-dbpassword
      namespace: applications

