apiVersion: v1 # Includes the Service for lazyness
kind: Service
metadata:
  name: postgres-svc
  labels:
    app: postgress
spec:
  ports:
  - port: 6379
    name: web
  clusterIP: None
  selector:
    app: postgresapp
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-ss
spec:
  serviceName: postgres-svc
  selector:
    matchLabels:
      app: postgresapp
  template:
    metadata:
      labels:
        app: postgresapp
    spec:
      containers:
        - name: postgres
          image: postgres:13
          envFrom:
          - secretRef:
              name: postgres-dbpassword
          ports:
          - containerPort: 6379
            name: postgresdb
          volumeMounts:
            - name: data
              mountPath: /data
              subPath: postgres
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 100Mi