apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/configmap.yaml
- manifests/persistentvolume.yaml
- manifests/persistentvolumeclaim.yaml
- manifests/deployment.yaml
- manifests/service.yaml
- manifests/horizontalpodautoscaler.yaml
- manifests/ingress.yaml
images:
- name: APP/HASH_IMAGE
  newName: amadeuspham/kubernetes-main-app:1.1
- name: APP/TIME_IMAGE
  newName: amadeuspham/timesaver