apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-rate
spec:
  metrics:
  - name: cpu-rate
    initialDelay: 2m
    successCondition: result < 0.05
    provider:
      prometheus:
        address: http://kube-prometheus-stack-1602-prometheus.prometheus.svc.cluster.local:9090 # DNS name for my Prometheus, find yours with kubectl describe svc ...
        query: |
          scalar(
            sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace="project"}) -
            sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace="project"} offset 10m)
          )