apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: wiki-job
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: wiki-job
            image: PROJECT/IMAGE-WIKI
            env:
            - name: URL
              value: "https://en.wikipedia.org/wiki/Special:Random"
          restartPolicy: OnFailure