apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      serviceAccountName: todoksa
      containers:
        - name: todo-backend
          image: PROJECT/IMAGE_BACKEND
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: password
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: dbsecret
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: dbsecret
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: dbsecret
                  key: database
        - name: cloud-sql-proxy
          # It is recommended to use the latest version of the Cloud SQL proxy
          # Make sure to update on a regular schedule!
          image: gcr.io/cloudsql-docker/gce-proxy:1.17
          command:
            - "/cloud_sql_proxy"
            - "-instances=todo-instance=tcp:5432"
          securityContext:
            # The default Cloud SQL proxy image runs as the
            # "nonroot" user and group (uid: 65532) by default.
            runAsNonRoot: true