apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: PROJECT/IMAGE-BACKEND
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: password