apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- redis-config.yaml
- redis.yaml
# - sealedsecret.yaml
- sealedsecret_telegram.yaml
- rollout.yaml
- rollout-backend.yaml
- deployment-broadcaster.yaml
- analysistemplate.yaml
# - service.yaml
# - service-backend.yaml
# - horizontalpodautoscaler.yaml
# - horizontalpodautoscaler-backend.yaml
# - ingress.yaml
# - cronjob.yaml
images:
- name: PROJECT/IMAGE_FRONTEND
  newName: amadeuspham/kubernetes-todo:2.3
- name: PROJECT/IMAGE_BACKEND
  newName: amadeuspham/kubernetes-todo-backend:3.2
- name: PROJECT/IMAGE_WIKI
  newName: amadeuspham/kubernetes-wiki
- name: PROJECT/IMAGE_BROADCASTER
  newName: amadeuspham/kubernetes-broadcaster:1.4