apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# - sealedsecret.yaml
resources:
- redis-config.yaml
- redis.yaml
- sealedsecret_telegram.yaml
- rollout.yaml
- rollout-backend.yaml
- deployment-broadcaster.yaml
- analysistemplate.yaml
- service.yaml
- service-backend.yaml
- horizontalpodautoscaler.yaml
- horizontalpodautoscaler-backend.yaml
- ingress.yaml
- cronjob.yaml
images:
- name: PROJECT/IMAGE_BACKEND
  newName: amadeuspham/kubernetes-todo-backend
  newTag: 3717e92c202955f81b292aa4c582e9d74b76162d
- name: PROJECT/IMAGE_BROADCASTER
  newName: amadeuspham/kubernetes-broadcaster
  newTag: 3717e92c202955f81b292aa4c582e9d74b76162d
- name: PROJECT/IMAGE_FRONTEND
  newName: amadeuspham/kubernetes-todo
  newTag: 3717e92c202955f81b292aa4c582e9d74b76162d
- name: PROJECT/IMAGE_WIKI
  newName: amadeuspham/kubernetes-wiki
  newTag: 3717e92c202955f81b292aa4c582e9d74b76162d
