apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- todo-project/manifests/redis-config.yaml
- todo-project/manifests/redis.yaml
- todo-project/manifests/deployment.yaml
- todo-project/manifests/deployment-backend.yaml
- todo-project/manifests/service.yaml
- todo-project/manifests/service-backend.yaml
- todo-project/manifests/ingress.yaml
- todo-project/manifests/cronjob.yaml
images:
- name: PROJECT/IMAGE-FRONTEND
  newName: amadeuspham/kubernetes-todo
- name: PROJECT/IMAGE-BACKEND
  newName: amadeuspham/kubernetes-todo-backend
- name: PROJECT/IMAGE-WIKI
  newName: amadeuspham/kubernetes-wiki