apiVersion: apps/v1
kind: Deployment
metadata:
  name: hash-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hash
  template:
    metadata:
      labels:
        app: hash
    spec:
      volumes: # Define volume
        - name: shared-time
          persistentVolumeClaim:
            claimName: pingpong-claim
      containers:
        - name: hashgenerator
          image: APP/HASH_IMAGE
          volumeMounts: 
          - name: shared-time
            mountPath: /usr/src/app/files
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: hash-configmap
                  key: message
          envFrom:
          - secretRef:
              name: postgres-dbpassword
          resources:
            limits:
              cpu: "100m"
              memory: "100Mi"
          readinessProbe:
            initialDelaySeconds: 10 # Initial delay until the readiness is tested
            periodSeconds: 5 # How often to test
            httpGet:
               path: /healthz
               port: 5000
        - name: timesaver
          image: APP/TIME_IMAGE
          volumeMounts: 
          - name: shared-time
            mountPath: /usr/src/app/files
          resources:
            limits:
              cpu: "100m"
              memory: "100Mi"