apiVersion: apps/v1
kind: Deployment
metadata:
  name: hash-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hash
  template:
    metadata:
      labels:
        app: hash
    spec:
      volumes: # Define volume
        - name: shared-time
          persistentVolumeClaim:
            claimName: pingpong-claim
      containers:
        - name: hashgenerator
          image: amadeuspham/kubernetes-main-app
          volumeMounts: 
          - name: shared-time
            mountPath: /usr/src/app/files
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: hash-configmap
                  key: message
          envFrom:
          - secretRef:
              name: postgres-dbpassword
          resources:
            limits:
              cpu: "100m"
              memory: "100Mi"
        - name: timesaver
          image: amadeuspham/timesaver
          volumeMounts: 
          - name: shared-time
            mountPath: /usr/src/app/files
          resources:
            limits:
              cpu: "100m"
              memory: "100Mi"