name: Release application

on:
  push:

env:
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  FRONTEND_IMAGE: todo-dep
  BACKEND_IMAGE: todo-backend-dep
  WIKI_IMAGE: wiki-job

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}
    - run: gcloud --quiet auth configure-docker
    - run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
    - name: Create frontend image name and tag
      run: |
        echo "FRONTEND_IMAGE_WITH_TAG=gcr.io/${{ secrets.GKE_PROJECT }}/$FRONTEND_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA" >> $GITHUB_ENV
    - name: Create backend image name and tag
      run: |
        echo "BACKEND_IMAGE_WITH_TAG=gcr.io/${{ secrets.GKE_PROJECT }}/$BACKEND_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA" >> $GITHUB_ENV
    - name: Create wiki image name and tag
      run: |
        echo "WIKI_IMAGE_WITH_TAG=gcr.io/${{ secrets.GKE_PROJECT }}/$WIKI_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA" >> $GITHUB_ENV
    - name: Build frontend
      run: docker build --tag "${{ env.FRONTEND_IMAGE_WITH_TAG }}" .
      working-directory: todo-project/frontend
    - name: Publish frontend
      run: docker push "${{ env.FRONTEND_IMAGE_WITH_TAG }}"
      working-directory: todo-project/frontend
    - name: Build backend
      run: docker build --tag "${{ env.BACKEND_IMAGE_WITH_TAG }}" .
      working-directory: todo-project/backend
    - name: Publish backend
      run: docker push "${{ env.BACKEND_IMAGE_WITH_TAG }}"
      working-directory: todo-project/backend
    - name: Build wiki
      run: docker build --tag "${{ env.WIKI_IMAGE_WITH_TAG }}" .
      working-directory: todo-project/wiki-job
    - name: Publish wiki
      run: docker push "${{ env.WIKI_IMAGE_WITH_TAG }}"
      working-directory: todo-project/wiki-job
    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize
    - name: Deploy
      run: |-
        ./kustomize edit set image PROJECT/IMAGE_FRONTEND=$FRONTEND_IMAGE_WITH_TAG
        ./kustomize edit set image PROJECT/IMAGE_BACKEND=$BACKEND_IMAGE_WITH_TAG
        ./kustomize edit set image PROJECT/IMAGE_WIKI=$WIKI_IMAGE_WITH_TAG
        kubectl apply -k .
        kubectl rollout status deployment $FRONTEND_IMAGE
        kubectl rollout status deployment $BACKEND_IMAGE
        kubectl rollout status cronjob $WIKI_IMAGE